begin;
select no_plan();

insert into finance.households(id) values
 ('00000000-0000-4000-8000-00000000c001'), ('00000000-0000-4000-8000-00000000c101');
insert into finance.household_members(id,household_id,email,auth_user_id,role) values
 ('00000000-0000-4000-8000-00000000c002','00000000-0000-4000-8000-00000000c001','recon-a@test.invalid','00000000-0000-4000-8000-00000000c003','member'),
 ('00000000-0000-4000-8000-00000000c102','00000000-0000-4000-8000-00000000c101','recon-b@test.invalid','00000000-0000-4000-8000-00000000c103','member');
insert into public.accounts(account_id,source_account_id,name,household_id,source_system,currency_code,lifecycle_status) values
 ('00000000-0000-4000-8000-00000000c004','recon-liquid','Liquid','00000000-0000-4000-8000-00000000c001','test','ZAR','active'),
 ('00000000-0000-4000-8000-00000000c005','recon-card','Card','00000000-0000-4000-8000-00000000c001','test','ZAR','active'),
 ('00000000-0000-4000-8000-00000000c006','recon-restricted','Restricted','00000000-0000-4000-8000-00000000c001','test','ZAR','active'),
 ('00000000-0000-4000-8000-00000000c104','other-account','Other','00000000-0000-4000-8000-00000000c101','test','ZAR','active');
insert into finance.budget_account_settings(household_id,account_id,owner_scope,included,resource_class,freshness_hours,transaction_sign_convention,sign_evidence,actor_id) values
 ('00000000-0000-4000-8000-00000000c001','00000000-0000-4000-8000-00000000c004','shared',true,'liquid',24,'outflow_negative','statement','00000000-0000-4000-8000-00000000c002'),
 ('00000000-0000-4000-8000-00000000c001','00000000-0000-4000-8000-00000000c005','shared',true,'card',24,'outflow_negative','statement','00000000-0000-4000-8000-00000000c002'),
 ('00000000-0000-4000-8000-00000000c001','00000000-0000-4000-8000-00000000c006','shared',true,'restricted',24,'outflow_negative','statement','00000000-0000-4000-8000-00000000c002');
insert into public.snapshots(account_id,date,amount_cents,currency_code,household_id,source_system,observed_at) values
 ('00000000-0000-4000-8000-00000000c004',current_date,10000,'ZAR','00000000-0000-4000-8000-00000000c001','test',now()-interval '1 hour'),
 ('00000000-0000-4000-8000-00000000c005',current_date,100,'ZAR','00000000-0000-4000-8000-00000000c001','test',now()-interval '1 hour'),
 ('00000000-0000-4000-8000-00000000c006',current_date,100,'ZAR','00000000-0000-4000-8000-00000000c001','test',now()-interval '1 hour');

-- The helper refreshes both fingerprints immediately after each mutation. This
-- prevents an old fingerprint from making the assertion accidentally green.
do $$
declare h uuid:='00000000-0000-4000-8000-00000000c001'; c uuid:='00000000-0000-4000-8000-00000000c004'; p jsonb; f text; sf text; a timestamptz:=now()-interval '5 minutes'; got jsonb;
begin
 set local timezone='UTC';
 update public.accounts set lifecycle_status='active',archived_at=null where account_id=c; update public.accounts set lifecycle_status='archived',archived_at=now() where account_id in ('00000000-0000-4000-8000-00000000c005','00000000-0000-4000-8000-00000000c006');
 select finance.budget_settings_fingerprint(h,c),finance.budget_snapshot_fingerprint(h,c,current_date) into f,sf;
 p:=jsonb_build_object('schema_version',1,'evidence','source','utility_coverage',jsonb_build_object('status','not_required','evidence','none'),'accounts',jsonb_build_array(jsonb_build_object('account_id',c::text,'status','included','settings_fingerprint',f,'snapshot_date',current_date::text,'snapshot_fingerprint',sf,'balance_convention','cash_signed','activity_through',to_char(a at time zone 'UTC','YYYY-MM-DD"T"HH24:MI:SS.US"Z"'),'pending_included_ids','[]'::jsonb,'evidence','statement')));
 update public.snapshots set currency_code='EUR' where account_id=c and date=current_date; select finance.budget_snapshot_fingerprint(h,c,current_date) into sf; p:=jsonb_set(p,'{accounts,0,snapshot_fingerprint}',to_jsonb(sf)); got:=finance.budget_check_coverage(h,p,a); raise notice '%',is(got->'reasons'->0->>'code','snapshot_unverified_or_stale','invalid currency has exact reason'); raise notice '%',is(got->'coverage_snapshot'->'accounts'->0->>'normalized_cash_cents',null,'invalid currency has no normalized cash'); raise notice '%',is(got->'coverage_snapshot'->'accounts'->0->'snapshot_snapshot'->>'amount_cents','10000','invalid currency preserves amount');
 update public.snapshots set currency_code='ZAR',amount_cents=12.5 where account_id=c and date=current_date; select finance.budget_snapshot_fingerprint(h,c,current_date) into sf; p:=jsonb_set(p,'{accounts,0,snapshot_fingerprint}',to_jsonb(sf)); got:=finance.budget_check_coverage(h,p,a); raise notice '%',is(got->'reasons'->0->>'code','snapshot_unverified_or_stale','fraction has exact reason'); raise notice '%',is(got->'coverage_snapshot'->'accounts'->0->>'normalized_cash_cents',null,'fraction has no normalized cash');
 update public.snapshots set amount_cents='NaN'::numeric where account_id=c and date=current_date; select finance.budget_snapshot_fingerprint(h,c,current_date) into sf; p:=jsonb_set(p,'{accounts,0,snapshot_fingerprint}',to_jsonb(sf)); got:=finance.budget_check_coverage(h,p,a); raise notice '%',is(got->'reasons'->0->>'code','snapshot_unverified_or_stale','NaN has exact reason'); raise notice '%',is(got->'coverage_snapshot'->'accounts'->0->>'normalized_cash_cents',null,'NaN has no normalized cash');
 update public.snapshots set amount_cents='Infinity'::numeric where account_id=c and date=current_date; select finance.budget_snapshot_fingerprint(h,c,current_date) into sf; p:=jsonb_set(p,'{accounts,0,snapshot_fingerprint}',to_jsonb(sf)); got:=finance.budget_check_coverage(h,p,a); raise notice '%',is(got->'reasons'->0->>'code','snapshot_unverified_or_stale','Infinity has exact reason'); raise notice '%',is(got->'coverage_snapshot'->'accounts'->0->>'normalized_cash_cents',null,'Infinity has no normalized cash');
 update public.snapshots set amount_cents=9223372036854775808 where account_id=c and date=current_date; select finance.budget_snapshot_fingerprint(h,c,current_date) into sf; p:=jsonb_set(p,'{accounts,0,snapshot_fingerprint}',to_jsonb(sf)); got:=finance.budget_check_coverage(h,p,a); raise notice '%',is(got->'reasons'->0->>'code','snapshot_unverified_or_stale','bigint overflow has exact reason'); raise notice '%',is(got->'coverage_snapshot'->'accounts'->0->>'normalized_cash_cents',null,'bigint overflow has no normalized cash');
 update public.snapshots set amount_cents=10000,currency_code='ZAR',observed_at=now()-interval '2 hours' where account_id=c and date=current_date; update finance.budget_account_settings set freshness_hours=1 where household_id=h and account_id=c; select finance.budget_settings_fingerprint(h,c),finance.budget_snapshot_fingerprint(h,c,current_date) into f,sf; p:=jsonb_set(jsonb_set(p,'{accounts,0,settings_fingerprint}',to_jsonb(f)),'{accounts,0,snapshot_fingerprint}',to_jsonb(sf)); got:=finance.budget_check_coverage(h,p,a); raise notice '%',is(got->'reasons'->0->>'code','snapshot_unverified_or_stale','old observation has exact reason'); raise notice '%',is(got->'coverage_snapshot'->'accounts'->0->>'normalized_cash_cents',null,'old observation has no normalized cash');
 update finance.budget_account_settings set freshness_hours=2 where household_id=h and account_id=c; got:=finance.budget_check_coverage(h,p,a); raise notice '%',is(got->'reasons'->0->>'code','settings_fingerprint_stale','stale settings fingerprint has exact reason'); raise notice '%',is(got->'coverage_snapshot'->'accounts'->0->>'normalized_cash_cents',null,'stale settings has no normalized cash');
 update finance.budget_account_settings set freshness_hours=2147483647 where household_id=h and account_id=c; update public.snapshots set observed_at=now()-interval '1 hour' where account_id=c and date=current_date; select finance.budget_settings_fingerprint(h,c),finance.budget_snapshot_fingerprint(h,c,current_date) into f,sf; p:=jsonb_set(jsonb_set(p,'{accounts,0,settings_fingerprint}',to_jsonb(f)),'{accounts,0,snapshot_fingerprint}',to_jsonb(sf)); begin got:=finance.budget_check_coverage(h,p,a); raise notice '%',is(got->>'status','complete','maximum freshness does not underflow timestamp arithmetic'); exception when others then raise notice '%',ok(false,'maximum freshness does not underflow timestamp arithmetic'); end;
end $$;

do $$
declare h uuid:='00000000-0000-4000-8000-00000000c001'; c uuid:='00000000-0000-4000-8000-00000000c005'; p jsonb; f text; sf text; a timestamptz:=now()-interval '5 minutes'; got jsonb;
begin
 set local timezone='UTC';
 update public.accounts set lifecycle_status='active',archived_at=null where account_id=c; update public.accounts set lifecycle_status='archived',archived_at=now() where account_id in ('00000000-0000-4000-8000-00000000c004','00000000-0000-4000-8000-00000000c006');
 update finance.budget_account_settings set freshness_hours=24 where household_id=h and account_id=c; update public.snapshots set amount_cents=100 where account_id=c and date=current_date; select finance.budget_settings_fingerprint(h,c),finance.budget_snapshot_fingerprint(h,c,current_date) into f,sf;
 p:=jsonb_build_object('schema_version',1,'evidence','card','utility_coverage',jsonb_build_object('status','not_required','evidence','none'),'accounts',jsonb_build_array(jsonb_build_object('account_id',c::text,'status','included','settings_fingerprint',f,'snapshot_date',current_date::text,'snapshot_fingerprint',sf,'balance_convention','debt_positive','activity_through',to_char(a at time zone 'UTC','YYYY-MM-DD"T"HH24:MI:SS.US"Z"'),'pending_included_ids','[]'::jsonb,'evidence','card')));
 got:=finance.budget_check_coverage(h,p,a); raise notice '%',is(got->>'status','complete','positive debt is complete'); raise notice '%',is(got->'coverage_snapshot'->'accounts'->0->>'normalized_debt_cents','100','positive debt normalizes');
 update public.snapshots set amount_cents=-100 where account_id=c and date=current_date; select finance.budget_snapshot_fingerprint(h,c,current_date) into sf; p:=jsonb_set(p,'{accounts,0,snapshot_fingerprint}',to_jsonb(sf)); got:=finance.budget_check_coverage(h,p,a); raise notice '%',is(got->'reasons'->0->>'code','card_debt_sign_contradiction','contradiction has exact reason');
 update public.snapshots set amount_cents=-100 where account_id=c and date=current_date; select finance.budget_snapshot_fingerprint(h,c,current_date) into sf; p:=jsonb_set(jsonb_set(p,'{accounts,0,balance_convention}','"debt_negative"'::jsonb),'{accounts,0,snapshot_fingerprint}',to_jsonb(sf)); got:=finance.budget_check_coverage(h,p,a); raise notice '%',is(got->>'status','complete','negative debt is complete'); raise notice '%',is(got->'coverage_snapshot'->'accounts'->0->>'normalized_debt_cents','100','negative debt normalizes');
 update public.snapshots set amount_cents=-9223372036854775808 where account_id=c and date=current_date; select finance.budget_snapshot_fingerprint(h,c,current_date) into sf; p:=jsonb_set(p,'{accounts,0,snapshot_fingerprint}',to_jsonb(sf)); got:=finance.budget_check_coverage(h,p,a); raise notice '%',is(got->'coverage_snapshot'->'accounts'->0->>'normalized_debt_cents','9223372036854775808','minimum bigint debt is a safe string');
end $$;

-- Account currency, observation age, date-only UTC fallback, and explicit gates.
do $$
declare h uuid:='00000000-0000-4000-8000-00000000c001'; c uuid:='00000000-0000-4000-8000-00000000c004'; p jsonb; f text; sf text; a timestamptz:='2026-01-02 00:30+00'; got jsonb;
begin
 set local timezone='UTC';
 update public.accounts set lifecycle_status='active',archived_at=null where account_id=c; update public.accounts set lifecycle_status='archived',archived_at=now() where account_id in ('00000000-0000-4000-8000-00000000c005','00000000-0000-4000-8000-00000000c006');
 update public.snapshots set amount_cents=10000,currency_code='ZAR',observed_at=a-interval '1 hour' where account_id=c and date=current_date; select finance.budget_settings_fingerprint(h,c),finance.budget_snapshot_fingerprint(h,c,current_date) into f,sf;
 p:=jsonb_build_object('schema_version',1,'evidence','activity','utility_coverage',jsonb_build_object('status','not_required','evidence','none'),'accounts',jsonb_build_array(jsonb_build_object('account_id',c::text,'status','included','settings_fingerprint',f,'snapshot_date',current_date::text,'snapshot_fingerprint',sf,'balance_convention','cash_signed','activity_through','2026-01-01T12:00:00.000000Z','pending_included_ids','[]'::jsonb,'evidence','statement')));
 update public.accounts set currency_code='EUR' where account_id=c; select finance.budget_snapshot_fingerprint(h,c,current_date) into sf; p:=jsonb_set(p,'{accounts,0,snapshot_fingerprint}',to_jsonb(sf)); got:=finance.budget_check_coverage(h,p,a); raise notice '%',is(got->'reasons'->0->>'code','snapshot_unverified_or_stale','account non-ZAR is incomplete'); update public.accounts set currency_code='ZAR' where account_id=c; select finance.budget_snapshot_fingerprint(h,c,current_date) into sf; p:=jsonb_set(p,'{accounts,0,snapshot_fingerprint}',to_jsonb(sf));
 insert into public.transactions(id,account_id,date,occurred_on,details,household_id,source_system,source_is_pending,source_is_archived) values('recon-date-only',c,timestamptz '2026-01-02 00:00+00',date '2026-01-02','{}',h,'test',false,false); set local timezone='UTC'; got:=finance.budget_check_coverage(h,p,a); raise notice '%',is(got->'reasons' @> '[{"code":"source_activity_unreconciled"}]'::jsonb,true,'date-only midnight is unreconciled under UTC'); set local timezone='Pacific/Kiritimati'; got:=finance.budget_check_coverage(h,p,a); raise notice '%',is(got->'reasons' @> '[{"code":"source_activity_unreconciled"}]'::jsonb,true,'date-only midnight is unreconciled under Kiritimati'); delete from public.transactions where id='recon-date-only';
 update finance.budget_account_settings set resource_class='restricted' where household_id=h and account_id=c; select finance.budget_settings_fingerprint(h,c) into f; p:=jsonb_set(p,'{accounts,0,settings_fingerprint}',to_jsonb(f)); got:=finance.budget_check_coverage(h,p,a); raise notice '%',is(got->'reasons' @> '[{"code":"restricted_resources_unverified"}]'::jsonb,true,'restricted is explicit gate'); update finance.budget_account_settings set resource_class='liquid' where household_id=h and account_id=c; select finance.budget_settings_fingerprint(h,c) into f; p:=jsonb_set(jsonb_set(p,'{accounts,0,settings_fingerprint}',to_jsonb(f)),'{utility_coverage,status}','"verified"'::jsonb); got:=finance.budget_check_coverage(h,p,a); raise notice '%',is(got->'reasons' @> '[{"code":"utilities_unverified"}]'::jsonb,true,'verified utility is explicit gate');
end $$;

-- Member RPC cutover/replay and state drift.  The privileged fingerprints are
-- computed before changing role, so this remains a real member-RPC test.
do $$
declare h uuid:='00000000-0000-4000-8000-00000000c001'; c uuid:='00000000-0000-4000-8000-00000000c004'; p jsonb; f text; sf text; a timestamptz:=now()-interval '5 minutes'; r jsonb; replay jsonb; rid uuid; conflict boolean:=false; got jsonb;
begin
 set local timezone='UTC';
 update public.accounts set lifecycle_status='active',archived_at=null where account_id=c; update public.accounts set lifecycle_status='archived',archived_at=now() where account_id in ('00000000-0000-4000-8000-00000000c005','00000000-0000-4000-8000-00000000c006');
 update finance.budget_account_settings set resource_class='liquid',freshness_hours=24 where household_id=h and account_id=c; update public.snapshots set amount_cents=10000,currency_code='ZAR',observed_at=now()-interval '1 hour' where account_id=c and date=current_date; select finance.budget_settings_fingerprint(h,c),finance.budget_snapshot_fingerprint(h,c,current_date) into f,sf;
 p:=jsonb_build_object('as_of',to_char(a at time zone 'UTC','YYYY-MM-DD"T"HH24:MI:SS.US"Z"'),'opening_fund_cutover',current_date::text,'notes','cutover','coverage_snapshot',jsonb_build_object('schema_version',1,'evidence','statement','utility_coverage',jsonb_build_object('status','not_required','evidence','none'),'accounts',jsonb_build_array(jsonb_build_object('account_id',c::text,'status','included','settings_fingerprint',f,'snapshot_date',current_date::text,'snapshot_fingerprint',sf,'balance_convention','cash_signed','activity_through',to_char(a at time zone 'UTC','YYYY-MM-DD"T"HH24:MI:SS.US"Z"'),'pending_included_ids','[]'::jsonb,'evidence','statement'))));
 perform set_config('request.jwt.claims',jsonb_build_object('sub','00000000-0000-4000-8000-00000000c003','role','authenticated','email','recon-a@test.invalid','email_verified',true)::text,true); perform set_config('request.jwt.claim.sub','00000000-0000-4000-8000-00000000c003',true); perform set_config('request.jwt.claim.role','authenticated',true); execute 'set local role authenticated'; r:=public.budget_record_reconciliation_v1('00000000-0000-4000-8000-00000000c201',p); rid:=(r->>'reconciliation_id')::uuid; raise notice '%',is(r->>'status','complete','member cutover complete'); replay:=public.budget_record_reconciliation_v1('00000000-0000-4000-8000-00000000c202',p||jsonb_build_object('opening_fund_cutover',null)); raise notice '%',is(replay->>'status','complete','null cutover does not reset'); begin perform public.budget_record_reconciliation_v1('00000000-0000-4000-8000-00000000c203',p||jsonb_build_object('opening_fund_cutover',(current_date-1)::text)); exception when sqlstate 'P0001' then conflict:=sqlerrm='budget_conflict: opening fund cutover is already established'; end; raise notice '%',ok(conflict,'different cutover is exact conflict');
 execute 'reset role'; update public.snapshots set amount_cents=10001 where account_id=c and date=current_date; execute 'set local role authenticated'; replay:=public.budget_record_reconciliation_v1('00000000-0000-4000-8000-00000000c201',p); raise notice '%',is(replay,r,'receipt replay returns original'); execute 'reset role'; got:=finance.budget_reconciliation_state(h,rid,now()); raise notice '%',is(got->>'status','incomplete','state detects snapshot drift');
end $$;

-- Forbidden pending ownership, pending drift, historic incomplete, and strict shape.
do $$
declare h uuid:='00000000-0000-4000-8000-00000000c001'; c uuid:='00000000-0000-4000-8000-00000000c004'; other uuid:='00000000-0000-4000-8000-00000000c005'; p jsonb; f text; sf text; a timestamptz:=now()-interval '5 minutes'; denied boolean:=false;
begin
 set local timezone='UTC';
 select finance.budget_settings_fingerprint(h,c),finance.budget_snapshot_fingerprint(h,c,current_date) into f,sf; p:=jsonb_build_object('schema_version',1,'evidence','x','utility_coverage',jsonb_build_object('status','not_required','evidence','x'),'accounts',jsonb_build_array(jsonb_build_object('account_id',c::text,'status','included','settings_fingerprint',f,'snapshot_date',current_date::text,'snapshot_fingerprint',sf,'balance_convention','cash_signed','activity_through',to_char(a at time zone 'UTC','YYYY-MM-DD"T"HH24:MI:SS.US"Z"'),'pending_included_ids','["foreign-pending"]'::jsonb,'evidence','x')));
 insert into public.transactions(id,account_id,date,details,household_id,source_system,source_is_pending,source_is_archived) values('foreign-pending',other,current_date,'{}','00000000-0000-4000-8000-00000000c101','test',true,false); begin perform finance.budget_check_coverage(h,p,a); exception when sqlstate 'P0001' then denied:=sqlerrm='budget_forbidden: pending transaction belongs to another household'; end; raise notice '%',ok(denied,'foreign pending exact forbidden'); delete from public.transactions where id='foreign-pending';
 p:=jsonb_set(p,'{accounts,0,pending_included_ids}','["wrong-account"]'::jsonb); insert into public.transactions(id,account_id,date,details,household_id,source_system,source_is_pending,source_is_archived) values('wrong-account',other,current_date,'{}',h,'test',true,false); denied:=false; begin perform finance.budget_check_coverage(h,p,a); exception when sqlstate 'P0001' then denied:=sqlerrm='budget_forbidden: pending transaction belongs to another account'; end; raise notice '%',ok(denied,'wrong account exact forbidden'); delete from public.transactions where id='wrong-account';
 denied:=false; begin perform finance.budget_validate_coverage(p||jsonb_build_object('unknown',1)); exception when sqlstate 'P0001' then denied:=sqlerrm like 'budget_invalid:%'; end; raise notice '%',ok(denied,'unknown key is budget_invalid'); denied:=false; begin perform finance.budget_validate_coverage(jsonb_set(p,'{accounts,0,pending_included_ids}','[1]'::jsonb)); exception when sqlstate 'P0001' then denied:=sqlerrm like 'budget_invalid:%'; end; raise notice '%',ok(denied,'wrong nested type is budget_invalid'); denied:=false; begin perform finance.budget_validate_coverage(p||jsonb_build_object('accounts',jsonb_build_array((p->'accounts')->0,(p->'accounts')->0))); exception when sqlstate 'P0001' then denied:=sqlerrm='budget_invalid: duplicate coverage account'; end; raise notice '%',ok(denied,'duplicate account is budget_invalid');
 update public.accounts set lifecycle_status='archived',archived_at=now() where household_id=h; p:=jsonb_build_object('schema_version',1,'evidence','empty','utility_coverage',jsonb_build_object('status','not_required','evidence','none'),'accounts','[]'::jsonb); begin perform finance.budget_validate_coverage(p); raise notice '%',ok(true,'empty coverage validates as evidence'); exception when sqlstate 'P0001' then raise notice '%',ok(false,'empty coverage validates as evidence'); end;
end $$;

-- A recorded incomplete pending assertion stays incomplete after the source is
-- repaired; changing its frozen source facts is separately visible as drift.
do $$
declare
  h uuid := '00000000-0000-4000-8000-00000000c001'; c uuid := '00000000-0000-4000-8000-00000000c004';
  f text; sf text; a timestamptz := now()-interval '5 minutes'; p jsonb; r jsonb; state jsonb;
begin
  set local timezone='UTC';
  update public.accounts set lifecycle_status='active',archived_at=null where account_id=c;
  update public.accounts set lifecycle_status='archived',archived_at=now() where household_id=h and account_id<>c;
  update finance.budget_account_settings set resource_class='liquid',freshness_hours=24 where household_id=h and account_id=c;
  update public.snapshots set amount_cents=10000,currency_code='ZAR',observed_at=now()-interval '1 hour' where account_id=c and date=current_date;
  insert into public.transactions(id,account_id,date,details,household_id,source_system,source_is_pending,source_is_archived,amount)
  values('recon-owned-pending',c,current_date,'{}',h,'test',true,false,-10);
  select finance.budget_settings_fingerprint(h,c),finance.budget_snapshot_fingerprint(h,c,current_date) into f,sf;
  p:=jsonb_build_object('as_of',to_char(a at time zone 'UTC','YYYY-MM-DD"T"HH24:MI:SS.US"Z"'),'notes','pending',
    'coverage_snapshot',jsonb_build_object('schema_version',1,'evidence','pending','utility_coverage',jsonb_build_object('status','not_required','evidence','none'),
      'accounts',jsonb_build_array(jsonb_build_object('account_id',c::text,'status','included','settings_fingerprint',f,'snapshot_date',current_date::text,'snapshot_fingerprint',sf,'balance_convention','cash_signed','activity_through',to_char(a at time zone 'UTC','YYYY-MM-DD"T"HH24:MI:SS.US"Z"'),'pending_included_ids','["recon-owned-pending"]'::jsonb,'evidence','pending'))));
  perform set_config('request.jwt.claims',jsonb_build_object('sub','00000000-0000-4000-8000-00000000c003','role','authenticated','email_verified',true)::text,true);
  perform set_config('request.jwt.claim.sub','00000000-0000-4000-8000-00000000c003',true); perform set_config('request.jwt.claim.role','authenticated',true); execute 'set local role authenticated';
  r:=public.budget_record_reconciliation_v1('00000000-0000-4000-8000-00000000c301',p); raise notice '%',is(r->>'status','incomplete','member records pending evidence as incomplete');
  execute 'reset role'; update public.transactions set source_is_pending=false,amount=-11 where id='recon-owned-pending';
  state:=finance.budget_reconciliation_state(h,(r->>'reconciliation_id')::uuid,now());
  raise notice '%',is(state->>'status','incomplete','historic incomplete cannot upgrade after pending repair');
  raise notice '%',is(state->'reasons' @> '[{"code":"pending_source_drift"},{"code":"historic_incomplete"}]'::jsonb,true,'pending mutation and historic incomplete are retained');
end $$;

set constraints all immediate;
select * from finish();
rollback;
