export const CATEGORY_CRITERIA: Record<string, string> = {
  "Bank Charges & Fees": "Bank fees, service charges, and card fees",
  "Card Repayments": "Payments toward a credit card balance",
  Cash: "Cash withdrawals or deposits",
  Cellphone: "Mobile phone airtime or contracts",
  Clothing: "Clothes, shoes, and apparel shops",
  Coffee: "Cafes and coffee purchases",
  Dividends: "Investment dividend income",
  "Eating Out & Takeaways": "Restaurants, fast food, and takeaways",
  Education: "Tuition, courses, and school fees",
  Entertainment: "Events, outings, and leisure",
  "Friends & Family": "Payments to or from people you know",
  "General Purchases": "Retail purchases that are not a more specific category",
  Gifts: "Gifts bought for other people",
  Groceries: "Supermarkets and grocery shops",
  Hobbies: "Hobby supplies and activities",
  "Vacation & Travel": "Flights, hotels, and holiday spend",
  "Home & Garden": "Household goods, furniture, and garden",
  Mortgage: "Home loan or bond payments",
  Insurance: "Insurance premiums",
  Interest: "Bank interest earned or charged",
  Investments: "Transfers into investment or TFSA accounts",
  Loans: "Loan repayments that are not the mortgage",
  Medical: "Doctors, pharmacy, and medical aid",
  "Personal Care": "Hair, grooming, and personal care",
  Pets: "Pet food, vets, and pet care",
  Internet: "Fibre, wifi, and internet service",
  "Professional Services": "Accountants, lawyers, and professional fees",
  Refunds: "Money returned for a previous purchase",
  Rent: "Rent payments",
  Rewards: "Cashback and reward credits",
  "Salaries & Wages": "Salary and wage income",
  Savings: "Transfers into savings",
  "Software & Services": "Software, cloud, and online subscriptions",
  "Sport & Fitness": "Sport clubs and fitness",
  Tax: "Tax payments or refunds",
  Transfers: "Moves between your own accounts",
  "Transport & Fuel": "Fuel and everyday transport",
  "Vehicle Expenses": "Car repairs, finance, and vehicle costs",
  Donations: "Charitable or church giving",
  Housekeeping: "Cleaning and domestic help",
  "Water & Electricity": "Municipal utilities",
  "Work Eats": "Food paid for work, including the office canteen",
  Flowers: "Florist purchases",
  Other: "Does not fit a more specific category",
  "Transport Parking": "Parking fees",
  "Transport Other": "Ride-hailing and other transport that is not fuel or parking",
  "Health & Fitness": "Health and fitness memberships",
};

export function criterionFor(name: string): string {
  return CATEGORY_CRITERIA[name] ?? name;
}
