name: Daily fetch

on:
  schedule:
    - cron: "11 6 * * *"

  workflow_dispatch:

jobs:
  # --- JOB 1: EXTRACT & LOAD SNAPSHOTS ---
  sync-snapshots:
    runs-on: ubuntu-latest
    steps:
      - name: Sleep for a random duration
        run: sleep $((RANDOM % 201))
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install dependencies
        run: yarn install
      - name: Run Snapshot Sync
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
          MY_22SEVEN_USERNAME: ${{ secrets.MY_22SEVEN_USERNAME }}
          MY_22SEVEN_PASSWORD: ${{ secrets.MY_22SEVEN_PASSWORD }}
        run: yarn tsx apps/src/functions/syncSnapshots.ts

  # --- JOB 2: EXTRACT & LOAD TRANSACTIONS ---
  sync-transactions:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Sleep for a random duration
        run: sleep $((RANDOM % 201))
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install dependencies
        run: yarn install
      - name: Run Transaction Sync
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
          MY_22SEVEN_USERNAME: ${{ secrets.MY_22SEVEN_USERNAME }}
          MY_22SEVEN_PASSWORD: ${{ secrets.MY_22SEVEN_PASSWORD }}
        run: yarn tsx apps/src/functions/syncTransactions.ts
